In this commit will have the all articles function added
rachelkwok00/fe-nc-news pull request #1
Opened 2023-10-23 15:26 UTC by rachelkwok00

2023-10-23 15:36 UTC, B7Bprog requested changes
Hey Rachel, please see my comments and refactor your code. Then please send us another PR.

2023-10-23 15:36 UTC, B7Bprog commented on src/Components/AllArticles.jsx
> +                    <ArticleCard article={article}/>
It's great that you created an article card component to avoid having this one too large.

2023-10-23 15:36 UTC, B7Bprog commented on src/Components/AllArticles.jsx
> +    const [articles, setArticles] = useState([]);
Please add a state for loading here and render a message for the user conditionally while the articles are loading.

2023-10-23 15:36 UTC, B7Bprog commented on src/Components/Utils/apis.js
> +
Please use axios.create() here so you will have a base URL which can be used for all your request functions. (See NC Notes/Axios bottom of the page)

2023-10-23 15:36 UTC, B7Bprog commented on src/Components/Utils/apis.js
> +    return fetch('https://nc-news-13ym.onrender.com/api/articles').then((response) =>
Please use axios instead of 'fetch'.

2023-10-23 15:36 UTC, B7Bprog commented on src/App.css
> +  margin-bottom: 1rem;
Please try to make your app responsive. (css @media...)

2023-10-24 10:31 UTC, Jodiech reviewed
Nice work on refactoring! You have separated out your API calls into another file 👍 All good! 🚀

2023-10-24 10:41 UTC, merged